### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by mortii** [tlambert03/setup-qt-libs#63]
Hi, I get this warning when using v1:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tlambert03/setup-qt-libs@v1.`

Is this warning accurate, or am I doing something wrong?

Possibly relevant to #58, but I didn't want to revive it in case it's not the same problem.

**Comment by tlambert03** [comment]
it's accurate, we need to update here, thanks for the reminder :)

**Comment by mortii** [comment]
Beautiful, the warning is gone now :)
Thank you!
