### ISSUE TITLE
Missing libegl1-mesa

### ISSUE THREAD

**Issue by guiwitz** [tlambert03/setup-qt-libs#65]
Hi,

As reported on the [napari zulip chat](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Tests.20failing.20on.20Github.20linux-latest) , this action is currently failing on GitHub on linux-latest with the message ```Unable to locate package libegl1-mesa```. I think the issue is that the library only exists up to Ubuntu 23, but GitHub as recently changed ubuntu-latest to Ubuntu 24. There's a libegl1-mesa-dev which probably can be used as replacement but I didn't test that.

**Comment by tlambert03** [comment]
thanks @guiwitz, if you or anyone (@Czaki?) end up learning/testing what we should do to fix it here, let me know and I'd be happy to update it.

**Comment by Czaki** [comment]
> thanks @guiwitz, if you or anyone (@Czaki?) end up learning/testing what we should do to fix it here, let me know and I'd be happy to update it.

I will try to play with this in few days.

**Comment by psobolewskiPhD** [comment]
Looks like libegl1-mesa was a dummy package for `libegl1`, at least as far back as `focal`:
https://packages.ubuntu.com/focal/libegl1-mesa
24.04 (noble) dropped the dummy, just has `libegl1`:
https://packages.ubuntu.com/noble/libegl1

Further, according to: https://askubuntu.com/a/1520334
> Installing libgl1 and libglx-mesa0 instead of libgl1-mesa-glx will result in equivalent behaviour and should work on Ubuntu 18.04 and newer.
